# Generated by Django 4.2.30 on 2026-08-29 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่บันทึก')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='อุณหภูมิกาย (°C)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='อัตราการเต้นของหัวใจ/ชีพจร (ครั้ง/นาที)')),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='ความดันตัวบน (mmHg)')),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='ความดันตัวล่าง (mmHg)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='อัตราการหายใจ (ครั้ง/นาที)')),
                ('spo2', models.PositiveIntegerField(blank=True, null=True, verbose_name='ความอิ่มตัวของออกซิเจน SpO2 (%)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='accounts.familygroup', verbose_name='กลุ่มครอบครัว')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='accounts.lineuser', verbose_name='ผู้ป่วย')),
            ],
            options={
                'verbose_name': 'บันทึกสัญญาณชีพ',
                'verbose_name_plural': 'บันทึกสัญญาณชีพ (Vital Signs)',
                'db_table': 'health_vitalsign',
                'indexes': [models.Index(fields=['user', 'date'], name='health_vita_user_id_198f2c_idx')],
            },
        ),
    ]
