# Generated by Django 4.2.30 on 2026-08-29 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Emoji / Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
            ],
            options={
                'verbose_name': 'หมวดหมู่ความรู้',
                'verbose_name_plural': 'หมวดหมู่ความรู้ (Knowledge Categories)',
                'db_table': 'knowledge_knowledgecategory',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อบทความ')),
                ('content', models.TextField(verbose_name='เนื้อหาบทความ (HTML)')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='สรุปย่อ (Preview)')),
                ('is_published', models.BooleanField(default=True, verbose_name='สถานะเผยแพร่')),
                ('send_schedule', models.CharField(blank=True, choices=[('', 'ไม่ส่งอัตโนมัติ'), ('mon_thu', 'ส่งทุกวันจันทร์และพฤหัสบดี (14:00 น.)'), ('custom', 'กำหนดเวลาเอง')], default='', max_length=20, verbose_name='ตารางส่งแจ้งเตือน')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='knowledge.knowledgecategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'บทความความรู้',
                'verbose_name_plural': 'บทความความรู้ (Knowledge Articles)',
                'db_table': 'knowledge_knowledgearticle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='ไฟล์รูปภาพ Infographic')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='คำอธิบายใต้รูป')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับรูปภาพ')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledge.knowledgearticle', verbose_name='บทความ')),
            ],
            options={
                'verbose_name': 'รูปภาพ Infographic',
                'verbose_name_plural': 'รูปภาพ Infographic (Gallery Images)',
                'db_table': 'knowledge_image',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['category'], name='knowledge_k_categor_29e948_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['is_published'], name='knowledge_k_is_publ_0fb5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['send_schedule'], name='knowledge_k_send_sc_e9d4be_idx'),
        ),
    ]
