# Generated by Django 4.2.30 on 2026-08-29 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='รหัสครอบครัว (FGxxxxx)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'กลุ่มครอบครัว',
                'verbose_name_plural': 'กลุ่มครอบครัว (Family Groups)',
                'db_table': 'accounts_familygroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=50, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='ชื่อแสดงใน LINE')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุลจริง')),
                ('id_card', models.CharField(max_length=13, verbose_name='เลขบัตรประชาชน 13 หลัก')),
                ('age', models.PositiveIntegerField(verbose_name='อายุ (ปี)')),
                ('role', models.CharField(choices=[('patient', 'ผู้ป่วย (Patient)'), ('caregiver', 'ผู้ดูแล (Caregiver)')], max_length=10, verbose_name='บทบาท')),
                ('is_registered', models.BooleanField(default=False, verbose_name='สถานะลงทะเบียน')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ลงทะเบียน')),
                ('underlying_disease', models.TextField(blank=True, null=True, verbose_name='โรคประจำตัว (หมอ/พยาบาลกรอก)')),
                ('allergy', models.TextField(blank=True, null=True, verbose_name='ประวัติแพ้ยา')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.familygroup', verbose_name='กลุ่มครอบครัว')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน LINE',
                'verbose_name_plural': 'ผู้ใช้งาน LINE (LINE Users)',
                'db_table': 'accounts_lineuser',
                'indexes': [models.Index(fields=['line_user_id'], name='accounts_li_line_us_fe9616_idx'), models.Index(fields=['family'], name='accounts_li_family__daf033_idx')],
            },
        ),
    ]
