# Generated by Django 4.2.30 on 2026-09-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='role',
            field=models.CharField(choices=[('patient', 'ผู้ป่วย (Patient)'), ('caregiver', 'ผู้ดูแล (Caregiver)'), ('nurse', 'พยาบาล / ทีมวิจัย (Nurse)')], max_length=10, verbose_name='บทบาท'),
        ),
    ]
