# Generated by Django 4.2.30 on 2026-08-29 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily_check', 'เตือนเช็คอาการประจำวัน (09:00)'), ('sepsis_edu', 'ความรู้เซพซิสประจำสัปดาห์ (จ./พฤ.)'), ('non_response', 'เตือนติดตามเมื่อไม่ตอบแบบประเมิน'), ('emergency', 'แจ้งเตือนเคสฉุกเฉิน (Red/Yellow Flag)'), ('vital_sign', 'เตือนบันทึกสัญญาณชีพ (วันที่ 14/30)')], max_length=20, verbose_name='ประเภทการแจ้งเตือน')),
                ('message', models.TextField(verbose_name='ข้อความที่ส่ง')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ส่งสำเร็จแล้ว')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ส่งสำเร็จ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้างรายการ')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.familygroup', verbose_name='กลุ่มครอบครัว')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.lineuser', verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'บันทึกการแจ้งเตือน',
                'verbose_name_plural': 'บันทึกการแจ้งเตือน (Notification Logs)',
                'db_table': 'notification_notificationlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_sent'], name='notificatio_is_sent_ac9651_idx'), models.Index(fields=['created_at'], name='notificatio_created_f441eb_idx')],
            },
        ),
    ]
