# Generated by Django 4.2.30 on 2026-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='คำถาม')),
                ('answer', models.TextField(verbose_name='คำตอบ')),
                ('category', models.CharField(choices=[('general', 'ความรู้ทั่วไป (General)'), ('medication', 'การใช้ยาและการดูแล (Medication)'), ('emergency', 'อาการฉุกเฉิน (Emergency)'), ('recovery', 'การฟื้นฟูร่างกาย (Recovery)')], default='general', max_length=50, verbose_name='หมวดหมู่คำถาม')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
            ],
            options={
                'verbose_name': 'คำถาม-คำตอบ (FAQ)',
                'verbose_name_plural': 'คำถาม-คำตอบ (FAQ 33 ข้อ)',
                'db_table': 'faq_faq',
                'ordering': ['order', 'id'],
            },
        ),
    ]
